# Site
title: Genard Briane Ancero
bio: "Senior 3D Artist"
description: "Senior 3D Artist with combined 7 years of experience in triple A Videogame Industry, 3D Production Management and Metaverse Building. Experienced in modelling and texturing of different subjects architecture, environment art, props, weapons, vehicles and vegetation."
locale: en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Comments
disqus_shortname: default

# Social
analytics-id: "default"

# Other
background_image: https://media.githubusercontent.com/media/admoraguilar/admoraguilar.github.io/master/images/bg.gif
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
  - scope:
      path: ""
    values:
      title: Genard Briance Ancero
  - scope:
      path: ""
      type: posts
    values:
      permalink: "/blog/:title/"
      layout: post
      author:

# Jekyll
permalink: /blog/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed

# Plugins Dir
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
    old,
  ]
